### ISSUE TITLE
测试计划11/24

### ISSUE THREAD

**Issue by KakaruHayate** [KakaruHayate/DiffSinger#2]
分支：https://github.com/KakaruHayate/DiffSinger/tree/yousa-ling-official-production-%23219

本轮测试计划从openvpi/DiffSinger commit #219版本出发

该分支目前实装了三个最新的改动，分别是：

**1. ESM(Embedding Strength Modulator)**

源自 2212.03435 参考BiSinger

通过ESM模块让lang emb实现通过音素序列调整嵌入强度，可能对跨语言有积极效果，目前泠鸢AI使用的方案

**2.duration res**

目前模型使用的duration模型为fs2原版模型，可能是因为带残差的结构出现了过拟合，原版的fs2时长预测模型是不带残差的

目前模仿speedyspeech，加回了残差，并且缩小模型到3层**（已经默认缩小到3，训练原版dur模型请自行修改到5）**

据称效果有微小提升，考虑到参数量降低，存在意义

**3.lynxnet res with cond**

在以前，condition是不包含到backbone的残差中的，在这里为残差添加了condition信息

在ddsp6.1中测试有明显提升，待测试

```
develop_option:
  use_esm: true
  use_dur_res: true
  lynx_res_with_cond: true
```

可以通过修改config以上开关选择进行的实验项目

实验愉快🤔
